# Generated by Django 4.2.9 on 2024-01-10 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='loyha nomi')),
                ('price', models.CharField(max_length=100, verbose_name='loyha narxi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('description', models.TextField(verbose_name='loyha haqida')),
                ('link', models.URLField(blank=True, null=True, verbose_name='loyha urli')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myportfolio.category')),
            ],
            options={
                'verbose_name': 'loyha',
                'verbose_name_plural': 'loyhalar',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images/', verbose_name='loyha rasmi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myportfolio.projects')),
            ],
            options={
                'verbose_name': 'loyha rasmi',
                'verbose_name_plural': 'loyha rasmlari',
            },
        ),
    ]
