# Generated by Django 4.2.9 on 2024-01-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0002_rename_product_gallery_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersALL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tel', models.CharField(max_length=100)),
                ('massage', models.TextField()),
            ],
        ),
    ]
