# Generated by Django 4.2.9 on 2024-01-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0003_usersall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersall',
            old_name='massage',
            new_name='message',
        ),
    ]
